-- IML Control Sprint 9.2.1 - Safe Cloud Installer
-- This script is idempotent: it may be run more than once.

begin;

-- ---------- Users and roles ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'viewer' check (role in ('admin','manager','viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles
for select to authenticated using (id = auth.uid());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),'viewer')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles(id,email,full_name,role)
select id,email,coalesce(raw_user_meta_data->>'full_name',''),'viewer'
from auth.users
on conflict (id) do update set email = excluded.email;

-- Preserve the existing administrator assignment when the user exists.
update public.profiles
set role='admin', is_active=true, updated_at=now()
where lower(email)=lower('lbenelisha@gmail.com');

create or replace function public.iml_is_admin()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active = true
  );
$$;

grant execute on function public.iml_is_admin() to authenticated;

-- Admins can read and manage all profiles. Users can still read their own profile.
drop policy if exists "admins read profiles" on public.profiles;
create policy "admins read profiles" on public.profiles
for select to authenticated using (public.iml_is_admin());

drop policy if exists "admins update profiles" on public.profiles;
create policy "admins update profiles" on public.profiles
for update to authenticated using (public.iml_is_admin()) with check (public.iml_is_admin());

-- ---------- Shared datasets ----------
create table if not exists public.iml_data_sources (
  kind text primary key check (kind in ('production','quality','deviations','targets','packaging_plan')),
  file_name text not null default '',
  row_count bigint not null default 0,
  raw_row_count bigint not null default 0,
  facilities integer not null default 0,
  loaded_at timestamptz not null default now(),
  loaded_by uuid references auth.users(id) on delete set null,
  loaded_by_email text not null default '',
  updated_at timestamptz not null default now()
);

-- Upgrade an older installation whose check constraint had only four kinds.
do $$
declare constraint_name text;
begin
  select conname into constraint_name
  from pg_constraint
  where conrelid = 'public.iml_data_sources'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%kind%';
  if constraint_name is not null then
    execute format('alter table public.iml_data_sources drop constraint %I', constraint_name);
  end if;
  alter table public.iml_data_sources
    add constraint iml_data_sources_kind_check
    check (kind in ('production','quality','deviations','targets','packaging_plan'));
exception when duplicate_object then null;
end $$;

create table if not exists public.iml_data_chunks (
  kind text not null references public.iml_data_sources(kind) on delete cascade deferrable initially deferred,
  chunk_index integer not null,
  payload jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  primary key (kind, chunk_index)
);

create table if not exists public.iml_upload_history (
  id bigint generated by default as identity primary key,
  kind text not null,
  file_name text not null default '',
  row_count bigint not null default 0,
  raw_row_count bigint not null default 0,
  uploaded_by uuid references auth.users(id) on delete set null,
  uploaded_by_email text not null default '',
  status text not null default 'success',
  error_message text not null default '',
  created_at timestamptz not null default now()
);

alter table public.iml_data_sources enable row level security;
alter table public.iml_data_chunks enable row level security;
alter table public.iml_upload_history enable row level security;

drop policy if exists "authenticated read iml sources" on public.iml_data_sources;
create policy "authenticated read iml sources" on public.iml_data_sources
for select to authenticated using (true);
drop policy if exists "admin manage iml sources" on public.iml_data_sources;
create policy "admin manage iml sources" on public.iml_data_sources
for all to authenticated using (public.iml_is_admin()) with check (public.iml_is_admin());

drop policy if exists "authenticated read iml chunks" on public.iml_data_chunks;
create policy "authenticated read iml chunks" on public.iml_data_chunks
for select to authenticated using (true);
drop policy if exists "admin manage iml chunks" on public.iml_data_chunks;
create policy "admin manage iml chunks" on public.iml_data_chunks
for all to authenticated using (public.iml_is_admin()) with check (public.iml_is_admin());

drop policy if exists "authenticated read upload history" on public.iml_upload_history;
create policy "authenticated read upload history" on public.iml_upload_history
for select to authenticated using (true);
drop policy if exists "admin insert upload history" on public.iml_upload_history;
create policy "admin insert upload history" on public.iml_upload_history
for insert to authenticated with check (public.iml_is_admin());

create index if not exists iml_data_chunks_kind_idx on public.iml_data_chunks(kind, chunk_index);
create index if not exists iml_upload_history_created_idx on public.iml_upload_history(created_at desc);

-- Enable change notifications for the small metadata table. Ignore if already enabled.
do $$
begin
  alter publication supabase_realtime add table public.iml_data_sources;
exception when duplicate_object then null;
end $$;

commit;
